# Generated by Django 5.1.2 on 2024-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='memo',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Напишите отзыв'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Укажите Ваше имя'),
        ),
    ]
