# Generated by Django 5.1.2 on 2024-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedbacks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Укажите Ваше имя'),
        ),
    ]
