# Generated by Django 5.1.2 on 2024-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedbacks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='user',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='description',
            field=models.TextField(default=1, max_length=2000, verbose_name='Напишите отзыв'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_completed',
            field=models.DateTimeField(blank=True, verbose_name='Дата'),
        ),
    ]
