# Generated by Django 5.1.2 on 2024-11-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_feedbacks_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='description',
            new_name='memo',
        ),
    ]
