# Generated by Django 5.1.2 on 2024-11-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_rename_description_feedbacks_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='created',
        ),
    ]
