# Generated by Django 5.1.2 on 2024-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_feedbacks_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='important',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Укажите Ваше имя'),
        ),
    ]
