# Generated by Django 5.1.2 on 2024-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_feedbacks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='e-mail'),
        ),
    ]
